.TH "serial.h" 3 "Tue Mar 19 2019" "Version 0.2.0" "foh-serial" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serial.h \- Header for dealing with serial communication\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstdio>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <cerrno>\fP
.br
\fC#include <climits>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <termios\&.h>\fP
.br
\fC#include <cctype>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <sys/resource\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/un\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFOHSerial\fP"
.br
.RI "Class for defining a serial port in software\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header for dealing with serial communication\&. 

Copyright (C) 2018 Dario Dorando (Faseroptik Henning GmbH)
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&.
.PP
\fBAuthor:\fP
.RS 4
Dario Dorando (Faseroptik Henning GmbH) 
.RE
.PP
\fBDate:\fP
.RS 4
06/09/2018 
.RE
.PP

.PP
Definition in file \fBserial\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for foh-serial from the source code\&.
